# Generated by Django 5.1.6 on 2025-02-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biofilter',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.CharField(max_length=35)),
                ('updated_at', models.CharField(max_length=35)),
                ('deleted_at', models.CharField(blank=True, max_length=30, null=True)),
                ('nitrate', models.DecimalField(decimal_places=7, max_digits=11)),
                ('nitrite', models.DecimalField(decimal_places=8, max_digits=11)),
                ('ammonia', models.DecimalField(decimal_places=9, max_digits=11)),
                ('timestamp', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'water_biofilter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.CharField(max_length=35)),
                ('updated_at', models.CharField(max_length=35)),
                ('deleted_at', models.CharField(blank=True, max_length=30, null=True)),
                ('air_temperature', models.DecimalField(decimal_places=8, max_digits=11)),
                ('relative_humidity', models.DecimalField(decimal_places=8, max_digits=11)),
                ('co2_level', models.BooleanField()),
                ('illumination_intensity', models.DecimalField(decimal_places=9, max_digits=13)),
                ('timestamp', models.CharField(max_length=16)),
                ('sensor_id', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'greenhouse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'useraccounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaterBed',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.CharField(max_length=35)),
                ('updated_at', models.CharField(max_length=35)),
                ('deleted_at', models.CharField(blank=True, max_length=30, null=True)),
                ('water_temperature', models.DecimalField(decimal_places=8, max_digits=11)),
                ('dissolved_O2_level', models.DecimalField(decimal_places=9, max_digits=11)),
                ('electrical_conductivity', models.IntegerField(max_length=11)),
                ('total_dissolved_solids', models.IntegerField(max_length=11)),
                ('nitrate', models.DecimalField(decimal_places=6, max_digits=11)),
                ('nitrite', models.DecimalField(decimal_places=8, max_digits=11)),
                ('ammonia', models.DecimalField(decimal_places=9, max_digits=11)),
                ('ph_level', models.DecimalField(decimal_places=9, max_digits=11)),
                ('timestamp', models.CharField(max_length=16)),
                ('sensor_id', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'water_bed',
                'managed': False,
            },
        ),
    ]
